# Generated by Django 5.2.5 on 2025-08-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('PLAN_UNSPECIFIED', 'Unspecified Plan'), ('PLAN_BASE_TRAINING', 'Base Training'), ('PLAN_TWELVE_WEEK_MARATHON', '12-Week Marathon Training Plan')], default='PLAN_UNSPECIFIED', max_length=50),
        ),
    ]
