# Generated by Django 5.2.5 on 2025-08-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_plan_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
    ]
