# Generated by Django 5.2.5 on 2025-08-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_remove_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('PLAN_PERSONALIZED_COACHING', 'Personalized Coaching'), ('PLAN_TWELVE_WEEK_MARATHON', '12-Week Marathon Training Plan')], default='PLAN_PERSONALIZED_COACHING', max_length=50),
        ),
    ]
