# Generated by Django 5.2.5 on 2025-08-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_plan_price_plan_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
