# Generated by Django 5.2.5 on 2025-08-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_plan_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('PLAN_PERSONALIZED_COACHING', 'Personalized Coaching'), ('PLAN_TWELVE_WEEK_MARATHON', '12-Week Marathon Training'), ('PLAN_STRENGTH_COACHING', 'Strength Programming')], default='PLAN_PERSONALIZED_COACHING', max_length=50),
        ),
    ]
