# Generated by Django 5.2.5 on 2025-08-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_price_remove_plan_price_remove_plan_price_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
