# Generated by Django 5.2.5 on 2025-08-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_delete_planprice_plan_price_plan_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='key_features',
            field=models.TextField(blank=True),
        ),
    ]
