# Generated by Django 5.2.5 on 2025-08-28 21:05

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('enrollment_status', models.CharField(choices=[('EXPRESSED_INTEREST', 'Expressed Interest'), ('ENROLLED', 'Enrolled'), ('RETIRED', 'Retired')], default='EXPRESSED_INTEREST', max_length=20)),
            ],
        ),
    ]
