# Generated by Django 5.2.5 on 2025-08-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.FloatField()),
                ('plan_id', models.FloatField()),
                ('star_rating', models.IntegerField()),
                ('review_text', models.TextField()),
            ],
        ),
    ]
