# Generated by Django 5.2.5 on 2025-08-28 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_phone_number'),
        ('plans', '0001_initial'),
        ('testimonials', '0002_remove_testimonial_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='plan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan'),
        ),
    ]
